spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: SPRING_DATASOURCE_URL
    hikari:
      username: SPRING_DATASOURCE_USERNAME
      password: SPRING_DATASOURCE_PASSWORD

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true